name: exwas_pipeline
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - astor=0.8.1
  - asttokens=2.0.5
  - autograd=1.6.2
  - autograd-gamma=0.5.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - boltons=23.0.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - cached_property=1.5.2
  - certifi=2024.7.4
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - comm=0.1.2
  - conda-content-trust=0.1.3
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - contourpy=1.0.5
  - cryptography=39.0.0
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.4.9
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - forestplot=0.3.1
  - formulaic=0.6.6
  - freetype=2.12.1
  - future=0.18.3
  - giflib=5.2.1
  - glib=2.69.1
  - graphlib-backport=1.0.3
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - interface_meta=1.3.0
  - ipykernel=6.19.2
  - ipython=8.8.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - jsonpatch=1.32
  - jsonpointer=2.0
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=12.2.0
  - libllvm10=10.0.1
  - libnsl=2.0.0
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - lifelines=0.27.8
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - matplotlib-venn=0.11.9
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=5.1.0
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nspr=4.35
  - nss=3.74
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openpyxl=3.0.10
  - openssl=3.0.14
  - packaging=23.1
  - pandas=1.5.2
  - parso=0.8.3
  - patsy=0.5.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=22.3.1
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.4.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyaml=21.10.1
  - pycosat=0.6.4
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyreadr=0.5.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.7
  - pyyaml=6.0.1
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - ranger-fm=1.9.3
  - readline=8.1.2
  - requests=2.28.2
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - seaborn=0.12.2
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - soupsieve=2.5
  - sqlite=3.40.1
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - threadpoolctl=3.2.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2022g
  - urllib3=1.26.14
  - wcwidth=0.2.5
  - wheel=0.37.1
  - wrapt=1.15.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - distinctipy==1.2.2
      - pyqt5-sip==12.11.0
