# this is the configuration file for all inputs used in the ExWAS pipeline
# Baesd on pipeline created by Ethan Kreuzer, obtained from github on Aug 30, 2024

---



programs: &programs
  # general
  bcftools: &bcftools ""
  tabix: &tabix ""
  apptainer: &apptainer ""
  plink: &plink ""
  plink2: &plink2 ""

  # For annotations
  vep_docker_image: &vep_docker_image ""
  vep_cache_dir: &vep_cache_dir ""
  vep_plugin_dir: &vep_plugin_dir ""
  

  # for nextflow pipeline
  Regenie_input_prep_scripts: &Regenie_input_prep_scripts ""


annotation_consequence_orders: &annotation_consequence_orders
  # https://usf.app.box.com/s/p2etici4mp5noboju6g0mnqfjx8ymwzd
  # also found in vep header
  # this defines which consequence to keep for each plugin across transcripts

  # determines which direction is more severe (higher or lower)
  CONST_NUMERIC: {
    "CADD_phred":"higher"
  }

  # the order of severity from most to least (left to right)
  CONST: {
    IMPACT: ["HIGH","MODERATE","LOW","MODIFIER"],
    LoF: ["HC","LC"],
    # alphamissense order
    ## P: Pathogenic
    ## B: Benign
    ## A: Ambiguous
    AlphaMissense_pred:["P","B","A"],

    # EVE class 25 order
    ## P: pathogenic
    ## B: benign
    ## U: uncertain
    EVE_Class25_pred:["P","B","U"],

    # LRT_pred order
    ## D: deleterious
    ## N: neutral
    ## U: unknown
    LRT_pred: ["D","N","U"],


    # mutation taster order
    #: automatic before non-automatic https://www.mutationtaster.org/info/documentation.html
    ## A: disease_causing_automatic
    ## D: Disease causing
    ## N: Polymorphism
    ## P: Polymorishm automatic  
    MutationTaster_pred:["A","D","P","N"],

    # polyphen2 hdiv order
    ## D: "probably damaging", HDIV score in [0.957,1] or rankscore in [0.55859,0.91137]
    ## P: "possibly damaging", HDIV score in [0.454,0.956] or rankscore in [0.37043,0.55681]
    ## B: "benign", HDIV score in [0,0.452] or rankscore in [0.03061,0.36974]
    Polyphen2_HDIV_pred:["D","P","B"],

    # polyphen2 hvar order
    ## D: "probably damaging", HVAR score in [0.909,1] or rankscore in [0.65694,0.97581]
    ## P: "possibly damaging", HVAR in [0.447,0.908] or rankscore in [0.47121,0.65622]
    ## B: "benign", HVAR score in [0,0.446] or rankscore in [0.01493,0.47076]
    Polyphen2_HVAR_pred:["D","P","B"],

    # SIFT4G pred order
    ## D: Damaging
    ## T: Tolerated
    SIFT4G_pred: ["D","T"],
    
    # SIFT pred order
    ## D: Damaging
    ## T: Tolerated
    SIFT_pred: ["D","T"]
  }


annotation_inputs: &annotation_inputs 
  # plugins are assumed to be in vep_plugins_dir
  # plugin arguments are assumed to be in vep_cache_dir
  ## loftee was installed in the vep apptainer image already

  # use $vep_cache_dir and $vep_plugins_dir in place of absolute path. 
  # Will be replaced accordingly in script

  vep_plugins: &vep_plugins [
    # loftee
    "LoF,loftee_path:$vep_plugins_dir,human_ancestor_fa:$vep_cache_dir/human_ancestor.fa.gz,conservation_file:$vep_cache_dir/loftee.sql,gerp_bigwig:$vep_cache_dir/gerp_conservation_scores.homo_sapiens.GRCh38.bw",
    # CADD  
    "CADD,snv=$vep_cache_dir/whole_genome_SNVs.tsv.gz",
    # dbNSFP
    "dbNSFP,$vep_cache_dir/dbNSFP4.8a_grch38.gz,gnomAD_genomes_AFR_AF,gnomAD_genomes_AMI_AF,gnomAD_genomes_AMR_AF,gnomAD_genomes_ASJ_AF,gnomAD_genomes_EAS_AF,gnomAD_genomes_FIN_AF,gnomAD_genomes_MID_AF,gnomAD_genomes_NFE_AF,gnomAD_genomes_SAS_AF,EVE_Class25_pred,VEP_canonical,LRT_pred,SIFT_pred,SIFT4G_pred,MutationTaster_pred,Polyphen2_HDIV_pred,Polyphen2_HVAR_pred,AlphaMissense_pred"
  ]




vcf_alignment: &vcf_alignment
  reference_fasta: &reference_fasta ""

regenie_annotation_mask: &regenie_annotation_mask
  # defines the masks to be created
  ## these are the mask names for each ExWAS study
  ## Each ExWAS study may have 1 or more masks
  ## the criteria for each mask is the value
  ### {study_name:{mask_name:mask_definitions}}
  mask_names: &mask_names {{
    "regeneron":{
      "M1":"LoF",
      "M2":"LoF,CADD>20",
      "M3":"LoF,CADD>10,CADD>20"
    },
    "g_england":{"M1":"LoF"}
  }}

  # 1 variant could have 1 or more criteria above (e.g., can be LoF and CADD>20). This specifies which one to pick in orders left to right.
  # this is across all masks
  plugin_orders: &plugin_orders {
    "regeneron":["LoF","CADD>20","CADD>10"],
    "g_england":["LoF"]
  }

  # The definitions for each masks
  ## this is what will be used to parse the vep output to generate the study specific annotation file
  ## i.e., what does CADD>20
  ## e.g.,: in regeneron:
  ###  - LoF: means variant annotated as HC by the LoF plugin
  ### - CADD>20: means variant with values above 20 in CADD_phred so these variants are annotaed as "CADD>20"
  ## Different studies may have different definitions
  mask_definitions: &mask_definitions 
    {
      "regeneron": {
        # LoF for study named 'regeneron' is only HC
        "LoF": {"LoF":["HC"]},
        # as CADD_phred is  defined as higher in CONST_NUMERIC
        # this will be greater than or equal to 20
        "CADD>20":{"CADD_phred":20}, 
        "CADD>10":{"CADD_phred":10}
      },
      "g_england":{
        # for example: LoF for study named "g_england" are either HC or LC
        "LoF":{"LoF":["HC","LC"]}
      }
    }
  


  ## VEP column names expected in files
  vep_variant_ID: &vep_variant_ID "#Uploaded_variation"
  vep_variant_location: &vep_variant_location "Location"
  vep_gene: &vep_gene "Gene"
  vep_annotations: &vep_annotations "Extra"

regenie_burden_testing: &regenie_burden_testing
  # Provide all flags except for output flags which will be determined based on input file names
  
  ## keys will be passed as is to Regenie so must be valid Regenie flags
  ## flags with no inputs should be left as empty string
  


  # Step 1 parameters
  s1_params: &s1_params {
    "--bed":"",
    "--covarFile":"",
    "--phenoFile":"",
    "--keep":"",
    "--phenoCol":"Trait",
    "--covarColList":"",
    "--catCovarList":"",
    "--bsize":"1000",
    "--lowmem":"",
    "--lowmem-prefix":"tmp_rg_trait",
  }

  # Step 2 (burden testing parameters)
  s2_params: &s2_params {
    "--aaf-bins" : "0.05,0.01",
    "--ref-first":"",
    "--bt":"",
    "--firth":"",
    "--approx":"",
    "--phenoCol":"TRAIT",
    "covarColClist":"Age,Age_square,sex_age_interaction",
    "catCovarList":"biological_sex",
    "vc-tests":"skato",
    "vc-maxAAF":"0.01",
    "--build-mask":"max",
    "--joint":"acat",
    "--bsize":"200"
  }

proj_config: &proj_config
  <<: *programs
  <<: *annotation_inputs
  <<: *annotation_consequence_orders
  <<: *vcf_alignment
  <<: *regenie_annotation_mask
  <<: *regenie_burden_testing

  # the input file must be in this build
  genome_build: &genome_build "GRCh38"

